### PR TITLE
Log useful information on reorg

### PR DESCRIPTION
**Pull request by jbearer**
Closes #<issue number>.

### Reviewers

Main reviewers:

- @John
- @Doe

Codeowner reviewers:

- @Alice
- @Bob

### CODE REVIEW

**Review by Ancient123 — APPROVED** [review]

**Comment by alice** [comment]
Is there a template somewhere with those placeholder names? I keep getting spam like this.

**Comment by Ancient123** [comment]
Oof. I'm sorry. We can get that fixed tomorrow. 😬

**Comment by jbearer** [comment]
Hahaha sorry about that!

**Comment by alice** [comment]
:D thank you!

**Pull request merged**
